/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const ElT: typeof import('element-plus/es')['ElT']
  const ElTr: typeof import('element-plus/es')['ElTr']
  const ElTre: typeof import('element-plus/es')['ElTre']
  const ElTree: typeof import('element-plus/es')['ElTree']
}
